#pragma once

namespace lines {

    struct Point {
        float x, y, z;

        Point(float xx, float yy, float zz)
            : x(xx), y(yy), z(zz) {}
    };

    struct Color {
        float r, g, b, a;

        Color() : r(0.0f), g(0.0f), b(0.0f), a(1.0f) {}

        Color(float rr, float gg, float bb, float aa)
            : r(rr), g(gg), b(bb), a(aa) {}
    };

    struct Segment {
        Point m_P0;
        Point m_P1;
	    Color m_Color;

        Segment(const Point p0, const Point p1, const Color color) :
            m_P0(p0), m_P1(p1), m_Color(color) {}
    };

    enum Types {
        CPU_GENERATED, // vertex buffer generated by CPU
        GPU_GENERATED, // vertex buffer generated by GPU using compute shader
        INSTANCING_BASED, // generated lines by instancing buffer
        INDIRECT_BASED, // instancing with indirect buffer filled with compute 
        TEXTURE_BASED // instancing with indirect usning text buffer
    };

    enum Caps {
        BUTT_CAP = 0,
        SQUARE_CAP = 1,
        ROUND_CAP = 2
    };

    enum Joins {
        ROUND_JOIN = 0,
        BEVEL_JOIN = 1,
        MITER_JOIN = 2
    };
}